x = input('Digite algo ')
print('O tipo primitivo desse valor é {}'.format(type(x)))
print('É um número? {}'.format(x.isnumeric()))
print('É composto apenas por letras? {}'.format(x.isalpha()))
print('É composto apenas por espaços? {}'.format(x.isspace()))
print('É alfanumérico? {}'.format(x.isalnum()))
print('Está em maiúsculas? {}'.format(x.isupper()))
print('Está em minusculas? {}'.format(x.islower()))
print('Está capitalizada? {}'.format(x.istitle()))

